version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile.prod
    image: nodeapp:1.0.0
    depends_on:
      - redis
    environment:
      REDIS_URL: redis
    networks:
      - default
    ports:
      - 8081:3000
    restart: always
    profiles:
      - app

  test:
    build:
      context: .
      dockerfile: dockerfile.test
    image: nodetest:1.0.0
    depends_on:
      - redis
    environment:
      REDIS_URL: redis
    networks:
      - default
    profiles:
      - test

  redis:
    image: redis:latest
    networks:
      - default
    ports:
      - 6379:6379
    restart: always