apiVersion: v2
name: nodeapp
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 16.13.1
    repository: https://charts.bitnami.com/bitnami

  - name: ingress-nginx
    version: 4.1.4
    repository: https://kubernetes.github.io/ingress-nginx