replicaCount: 1

image:
  repository: trydocker123/nodeapp
  pullPolicy: IfNotPresent
  tag: "latest"
  env:
    name: 'REDIS_URL'
    value: 'node-app-chart-redis-master'
  ports:
    containerPort: 3000
    hostPort: 8081

imagePullSecrets: []
nameOverride: "node-app-chart"
fullnameOverride: "node-app-chart"


serviceAccount:
  create: true
  annotations: {}
  name: "node-app-chart"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8081
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: node-app.local
      paths:
        - path: /
          pathType: Prefix

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

redis:
  architecture: standalone
  auth:
    enabled: false

tests:
  app:
    host: node-app.local